name: Java CI

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle test
      run: ./gradlew test

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Login to Github register
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images
      run: docker build . --file Dockerfile --tag petclinic

    - name:  Run Docker images
      run: docker run ghcr.io/helenagomezvillegas/petclinic:latest

    - name:  publish Docker images
      run: docker push ghcr.io/helenagomezvillegas/petclinic:latest








